fieldLayouts:
  6e8f865c-4018-4fc3-9096-23907596957e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eb82ac8d-c951-44c9-abc7-72ffdfee8121
            warning: null
            width: 100
          -
            fieldUid: fdc2e766-f2a8-4ee0-9ad8-9b7d64b8d86b # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ec6db4f-6596-4850-8992-778409ef0cd8
            warning: null
            width: 100
        name: Content
        uid: cacfe6ee-8bb8-45f5-9cd5-e9cec1ca1bd4
handle: index
hasTitleField: true
name: Index
section: b597a3a5-88d2-4446-9f93-a28351a1b666 # Index
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
