fieldLayouts:
  2c4a99e6-3070-4528-8e60-deca9f7a3e55:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c0390fe4-4c57-4832-80c9-2f02d39e49e8
            warning: null
            width: 100
          -
            fieldUid: cc3f9ff0-2259-4ed0-bcfc-b19a91dc4d67 # Customer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bd3e1a6-91c9-4899-97ba-67dcc9438a1f
            warning: null
            width: 100
          -
            fieldUid: 8b796e49-612b-4477-9567-64c11f929737 # Customer Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 663535a9-e913-42d3-a000-9b5b3d883e09
            warning: null
            width: 100
          -
            fieldUid: 68465f6c-a70b-4b6b-a3ab-feaece178361 # Customer Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 033ffe30-91f3-470e-b253-1137f2dd6d89
            warning: null
            width: 100
          -
            fieldUid: 7b80e1c3-fc1b-447d-a346-872ec9b0b853 # Card Token
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5680e5eb-5375-43ec-992b-d318efcee460
            warning: null
            width: 100
          -
            fieldUid: ecbbfebe-c824-4e29-b927-a3bcc10c9e24 # Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 760420d9-5ce3-4c32-bf75-f1e1471bfb4d
            warning: null
            width: 100
        name: Order
        uid: d6a98246-24a8-4d1f-af88-4cf98e28731e
handle: orders
hasTitleField: false
name: Orders
section: cc57a07c-7225-4ed5-8db2-31898436abb2 # Orders
sortOrder: 1
titleFormat: 'Order {id}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
