fieldLayouts:
  2efd489f-ca1a-488d-ac0b-2223cbba6899:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aee76664-a216-42a6-bd22-531044cd391e
            warning: null
            width: 100
          -
            fieldUid: 01fcd9d2-40bb-4f54-a225-7c9b674c3db9 # Plugin
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67a4f6cf-f552-44b1-b9a7-c13a215c358a
            warning: null
            width: 100
          -
            fieldUid: 69c15f3c-6ae1-4906-879f-495ab5c76102 # Craft License
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16dbde20-2ce3-4cae-8b1a-ea0556a55698
            warning: null
            width: 100
          -
            fieldUid: 4a4fdb04-6086-4fbd-b79f-1d99cefc9a31 # Domain
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc4b1882-0375-4d58-be1c-b7cbc099461d
            warning: null
            width: 100
          -
            fieldUid: 8965f5ae-4c8e-4529-bfc5-e7345e40d7ce # Auto Renew
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9e2b971-563e-4c0d-83f3-b7dcff2d6861
            warning: null
            width: 100
          -
            fieldUid: 1f6eaf1e-6f42-4dc2-86cb-62fd3665751a # Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8daa254-0b14-4d0c-aa0c-4c3bcc7f571b
            warning: null
            width: 100
        name: License
        uid: b201f2a3-032d-4672-84d9-b74e28e04917
handle: pluginLicense
hasTitleField: false
name: 'Plugin License'
section: bf872170-c29f-4188-9225-90e97869758b # Licenses
sortOrder: 1
titleFormat: 'Plugin License'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
