tabs:
  -
    elements:
      -
        attribute: payPalEmail
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        autofocus: false
        class: null
        disabled: false
        id: null
        instructions: null
        label: 'PayPal Email'
        mandatory: true
        max: null
        maxlength: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: false
        required: false
        size: null
        step: null
        tip: null
        title: null
        translatable: false
        type: craft\fieldlayoutelements\TextField
        uid: 0fba25b0-56fb-4155-8b09-571ddbb9e97d
        warning: null
        width: 100
      -
        fieldUid: db4da419-ca41-4a13-b4a4-9c3f59c217fd # Developer Name
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: d3676d0f-8523-4442-b82d-f2763745ff91
        warning: null
        width: 100
      -
        fieldUid: a4a501f3-5e4f-4708-99e6-69599fe86b31 # Developer URL
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: a8141e29-28f9-45b2-8f30-af697a6098ba
        warning: null
        width: 100
      -
        fieldUid: 4c92f946-0a98-4d19-8a70-ba643f88c1a0 # Business Address Line 1
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 91d5294a-bc36-4f11-a240-e644ed4a0835
        warning: null
        width: 100
      -
        fieldUid: b384f570-e131-42f9-8c20-8d0faacb734f # Business Address Line 2
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 6b18d044-1783-4f52-ba12-1b47e6ab6916
        warning: null
        width: 100
      -
        fieldUid: db187b36-568c-470a-ac7c-127e3a42f8b6 # Business City
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: a9fdeb85-6eb4-4ea6-b2d6-5080dcf0d0c2
        warning: null
        width: 100
      -
        fieldUid: 23676c77-087c-4f52-908d-3eee1deb6004 # Business Country
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 99e4edc8-f184-4cf5-b619-6d87e751644d
        warning: null
        width: 100
      -
        fieldUid: 205a826f-1701-41c7-804d-f7998cec0442 # Business Name
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 1fe22080-2ee4-48ea-9ed5-bb53d080b3e8
        warning: null
        width: 100
      -
        fieldUid: ea05b292-0026-4bec-a15c-1e09055223fc # Business State
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: a8d5b5b7-723b-4b33-978a-891fcc9d25fd
        warning: null
        width: 100
      -
        fieldUid: 34358d6d-9fda-49bb-a56d-f0fe2b05027f # Business VAT ID
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 4518be61-2854-4d0e-ba37-271ed8883254
        warning: null
        width: 100
      -
        fieldUid: 02269d9f-bbaa-4ea2-8b91-909e27e6ce05 # Business Zip Code
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f3e12446-257e-4e04-968e-83a6882822ae
        warning: null
        width: 100
      -
        fieldUid: a1deff4e-43ef-4a67-870e-813cfa36700c # Enable showcase features
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 0971731e-2204-43fb-b239-df63d881814d
        warning: null
        width: 100
      -
        fieldUid: 4234aa0a-59b0-4777-80ee-aeb7b931b924 # Enable Partner Features
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 77454f06-4352-4d0a-a820-1d35ac08629c
        warning: null
        width: 100
      -
        fieldUid: e76f9c9f-363c-476e-ae6d-c48eed173468 # Location
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 2d1f9a7b-9069-4763-8d27-795ea1186f50
        warning: null
        width: 100
      -
        fieldUid: 0ff67b0d-c811-4767-9d75-25472eee67a3 # Purchased Plugins
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 4058b23d-74e6-48ee-839f-801bd152de8a
        warning: null
        width: 100
    name: Profile
    uid: 049a85ea-a6cd-4a1c-8ccd-beb29c3b030a
  -
    elements:
      -
        fieldUid: 42b088ed-cffc-4382-aeb1-56e192d4138b # Support Plan
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: b833ec97-099b-4117-986d-42eca13aa812
        warning: null
        width: 100
      -
        fieldUid: bb6ba697-14a2-4342-baa5-c01d41641a48 # Support Plan Expiry Date
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 97c0b014-13df-4e46-8935-bcebcadcbc0b
        warning: null
        width: 100
    name: Support
    uid: 62f9ddd3-839e-4f11-a112-8fcccbf1b059
  -
    elements:
      -
        attribute: addresses
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\users\AddressesField
        uid: 627b63b9-f8fe-4175-a91e-fa453885008a
        warning: null
        width: 100
    name: Addresses
    uid: adfba2df-2fa2-4a6b-9801-5115cec56b3a
