fieldLayouts:
  87d607e6-5a47-4c6b-aaaa-d3ecb62c6e78:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: dc308b54-1f55-422f-a587-dacc6beae991
            warning: null
            width: 100
        name: Content
        uid: a6400b63-641d-43c4-a3ad-8e44eb555585
fs: $FS_ICONS
handle: icons
name: Icons
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
