fieldLayouts:
  ab0d2e58-eef4-483e-8d6d-8c737f635c83:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: bfbb250d-1e4e-4551-983c-2691277061fd
            warning: null
            width: 100
        name: Content
        uid: 9e814788-70ce-4b73-8594-a8f3c30477e6
fs: screenshots
handle: screenshots
name: Screenshots
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
