columnSuffix: null
contentColumnType: text
fieldGroup: a773b9fb-cbc5-423a-977f-8210c987176c # Store
handle: description
instructions: null
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
