columnSuffix: keucyoal
contentColumnType: text
fieldGroup: b20bbbda-6008-40ad-bd08-fff827696050 # Org
handle: partnerShortBio
instructions: null
name: 'Short Bio'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
