columnSuffix: bwuuixsu
contentColumnType: boolean
fieldGroup: b20bbbda-6008-40ad-bd08-fff827696050 # Org
handle: partnerIsCraftVerified
instructions: null
name: 'Is Craft Verified?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
