columnSuffix: ymbevoof
contentColumnType: boolean
fieldGroup: b20bbbda-6008-40ad-bd08-fff827696050 # Org
handle: partnerIsRegisteredBusiness
instructions: null
name: 'Is Registered Business?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
