columnSuffix: null
contentColumnType: string
fieldGroup: 4987fb8d-cf45-4b60-a94f-51c591336558 # License
handle: plugin
instructions: null
name: Plugin
searchable: true
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craftnet\fields\Plugins
