columnSuffix: null
contentColumnType: text
fieldGroup: ec01a46c-7aae-4b10-95ce-6ae6648b9745 # Plugin
handle: pluginHandle
instructions: null
name: 'Plugin Handle'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
