columnSuffix: byzvacpy
contentColumnType: boolean
fieldGroup: b20bbbda-6008-40ad-bd08-fff827696050 # Org
handle: requireOrderApproval
instructions: null
name: 'Require Order Approval'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
