description: null
handle: staff
name: Staff
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accesssitewhensystemisoff
  - 'assignusergroup:b64bf83a-40fd-48a4-ba39-455b7900f976' # Staff
  - 'assignusergroup:d17f6c64-5872-4457-8784-797b8c3e7ec8' # Developers
  - assignuserpermissions
  - 'craftnet:manageplugins'
  - 'createentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
  - 'createfolders:238dc7f2-e863-4b8f-96fa-805a3324dc5d' # Avatars
  - 'createfolders:495fa280-74b9-49af-8737-986532450386' # Screenshots
  - 'createfolders:fc4f52d6-458d-44cb-a2fd-f0042d715d64' # Icons
  - 'deleteentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
  - 'deletepeerentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
  - 'deletepeerentrydrafts:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
  - deleteusers
  - 'editsite:2a835d29-b3e4-4ef5-bf62-ad7285b4a4dd' # API
  - 'editsite:8928c23a-7002-467d-af97-333694b8dad8' # Console
  - 'editsite:dfc27822-23dd-49e2-ac3a-66a436674cf0' # Composer
  - editusers
  - registerusers
  - 'saveassets:238dc7f2-e863-4b8f-96fa-805a3324dc5d' # Avatars
  - 'saveassets:495fa280-74b9-49af-8737-986532450386' # Screenshots
  - 'saveassets:fc4f52d6-458d-44cb-a2fd-f0042d715d64' # Icons
  - 'saveentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
  - 'savepeerassets:238dc7f2-e863-4b8f-96fa-805a3324dc5d' # Avatars
  - 'savepeerassets:495fa280-74b9-49af-8737-986532450386' # Screenshots
  - 'savepeerassets:fc4f52d6-458d-44cb-a2fd-f0042d715d64' # Icons
  - 'savepeerentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
  - 'savepeerentrydrafts:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
  - 'utility:asset-indexes'
  - 'utility:clear-caches'
  - 'utility:db-backup'
  - 'utility:deprecation-errors'
  - 'utility:migrations'
  - 'utility:php-info'
  - 'utility:system-report'
  - 'utility:unavailable-plugins'
  - 'viewassets:238dc7f2-e863-4b8f-96fa-805a3324dc5d' # Avatars
  - 'viewassets:495fa280-74b9-49af-8737-986532450386' # Screenshots
  - 'viewassets:fc4f52d6-458d-44cb-a2fd-f0042d715d64' # Icons
  - 'viewentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
  - 'viewpeerassets:238dc7f2-e863-4b8f-96fa-805a3324dc5d' # Avatars
  - 'viewpeerassets:495fa280-74b9-49af-8737-986532450386' # Screenshots
  - 'viewpeerassets:fc4f52d6-458d-44cb-a2fd-f0042d715d64' # Icons
  - 'viewpeerentries:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
  - 'viewpeerentrydrafts:149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593' # Featured Plugins
