defaultPlacement: end
enableVersioning: true
handle: licenses
name: Licenses
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  8928c23a-7002-467d-af97-333694b8dad8: # Console
    enabledByDefault: true
    hasUrls: true
    template: licenses/_entry
    uriFormat: 'licenses/{slug}'
type: channel
